### ISSUE TITLE
redis-manager 无法使用

### ISSUE THREAD

**Issue by 961900940** [laravel-admin-extensions/redis-manager#19]
laravel-admin  版本5.8.27
按步骤添加扩展，本地启动redis服务后，访问 http://****/admin/redis 后，提示错误
查看  log viewer,显示
undefined index: none (View: D:\wamp\www\laravelAdmin\vendor\laravel-admin-ext\redis-manager\resources\views\index.blade.php)

**Comment by yljphp** [comment]
mee too

**Comment by z-song** [comment]
@961900940 @yljphp 提交了修复，更新版本

**Comment by 961900940** [comment]
在使用、添加  redis-manager 扩展之前，还依赖其他扩展吗？
需要先  添加 composer require predis/predis 吗？还有什么？




------------------ 原始邮件 ------------------
发件人: "lovepanpan"<notifications@github.com>; 
发送时间: 2019年7月10日(星期三) 晚上6:33
收件人: "laravel-admin-extensions/redis-manager"<redis-manager@noreply.github.com>; 
抄送: "ck"<961900940@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [laravel-admin-extensions/redis-manager] redis-manager 无法使用 (#19)




Closed #19.

**Comment by 961900940** [comment]
1）、过程中，需要  composer require predis/predis  这个命令吗？
2）、back扩展无法使用

Existing backups
         Backup         

     #NameDiskReachableHealthy# of backupsNewest backupUsed storage
1.Laravellocal✅❌0<error>No backups present</error>0 KB






------------------ 原始邮件 ------------------
发件人: "lovepanpan"<notifications@github.com>; 
发送时间: 2019年7月10日(星期三) 晚上6:33
收件人: "laravel-admin-extensions/redis-"<redis-manager@noreply.github.com>; 
抄送: "ck"<961900940@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [laravel-admin-extensions/redis-manager] redis-manager 无法使用 (#19)




@961900940 @yljphp 提交了修复，更新版本
